changeBorderColor
asenyk/4fun pull request #12
Opened 2020-06-12 14:01 UTC by reboot-ua

2020-06-12 16:48 UTC, OlegSkydonenko requested changes

2020-06-12 16:48 UTC, OlegSkydonenko commented on src/components/Signup.vue
> +        <input  type="text" class="form-control focused form-control-lg" v-model="firstName"/>
looks like you've added an excessive class, also remove please remove space character

2020-06-12 16:48 UTC, OlegSkydonenko commented on src/components/Signup.vue
> +        <input type="text" class="form-control form-control-lg" v-model="phoneNumber"/>
change type to "tel"

2020-06-12 16:48 UTC, OlegSkydonenko commented on src/components/Signup.vue
> +    border-color: #212529  !important;
please avoid using "!important"

2020-06-12 16:48 UTC, OlegSkydonenko commented on src/components/Signup.vue
> +
please remove an excessive blank lines

2020-06-13 11:05 UTC, asenyk approved these changes

2020-06-13 11:25 UTC, OlegSkydonenko approved these changes

2020-06-13 11:26 UTC, merged